name: grl
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - cmake=3.18.2
  - pip=20.3.3
  - python=3.6.12
  - pytorch=1.9
  - torchvision
  - torchaudio
  - cudatoolkit=11.1
  - pip:
    - absl-py==0.11.0
    - bayesian-optimization==1.2.0
    - cloudpickle==1.6.0
    - colorful==0.5.4
    - deepdish==0.3.6
    - dm-tree==0.1.5
    - filelock==3.0.12
    - gpustat==0.6.0
    - grpcio==1.35.0
    - grpcio-tools==1.35.0
    - gym==0.18.0
    - opencv-python==4.5.1.48
    - opencv-python-headless==4.3.0.36
    - pandas==1.1.5
    - pillow==7.2.0
    - protobuf==3.14.0
    - psutil==5.8.0
    - scipy==1.5.4
    - scikit-learn==0.24.1
    - ray[rllib]==1.0.1.post1
    - tensorboardx==2.1
    - termcolor==1.1.0
    - plotly==4.14.0
    - matplotlib==3.3.4
    - gym-minigrid==1.0.2
    - networkx==2.5
    - pyreap==0.9.1